#############################################################################
# Makefile for building: dist/tetrahedral_trees
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  TetrahedralTrees.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile TetrahedralTrees.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=native -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Isources -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = tetrahedral_trees1.0.0
DISTDIR = /home/ilfelle/Dropbox/Code_Projects/Tetrahedral_trees/build/tetrahedral_trees1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lrt 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = sources/utilities/sorting.cpp \
		sources/geometry/geometry.cpp \
		sources/geometry/geometry_distortion.cpp \
		sources/geometry/geometry_wrapper.cpp \
		sources/io/reader.cpp \
		sources/io/writer.cpp \
		sources/queries/border_checker.cpp \
		sources/queries/topological_queries.cpp \
		sources/tetrahedral_trees/reindexer.cpp \
		sources/utilities/input_generator.cpp \
		sources/utilities/string_management.cpp \
		sources/utilities/timer.cpp \
		sources/main.cpp \
		sources/queries/spatial_queries.cpp \
		sources/statistics/statistics.cpp \
		sources/basic_types/tetrahedron.cpp \
		sources/tetrahedral_trees/kd_subdivision.cpp \
		sources/tetrahedral_trees/ok_subdivision.cpp \
		sources/tetrahedral_trees/node_t.cpp 
OBJECTS       = build/sorting.o \
		build/geometry.o \
		build/geometry_distortion.o \
		build/geometry_wrapper.o \
		build/reader.o \
		build/writer.o \
		build/border_checker.o \
		build/topological_queries.o \
		build/reindexer.o \
		build/input_generator.o \
		build/string_management.o \
		build/timer.o \
		build/main.o \
		build/spatial_queries.o \
		build/statistics.o \
		build/tetrahedron.o \
		build/kd_subdivision.o \
		build/ok_subdivision.o \
		build/node_t.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		TetrahedralTrees.pro sources/basic_types/box.h \
		sources/basic_types/mesh.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/basic_types/vertex.h \
		sources/geometry/geometry.h \
		sources/geometry/geometry_distortion.h \
		sources/geometry/geometry_wrapper.h \
		sources/io/reader.h \
		sources/io/writer.h \
		sources/queries/border_checker.h \
		sources/queries/topological_queries.h \
		sources/queries/topological_queries_windowed.h \
		sources/statistics/full_query_statistics.h \
		sources/statistics/index_statistics.h \
		sources/statistics/query_statistics.h \
		sources/statistics/statistics.h \
		sources/tetrahedral_trees/kd_subdivision.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/ok_subdivision.h \
		sources/tetrahedral_trees/reindexer.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/subdivision.h \
		sources/utilities/input_generator.h \
		sources/utilities/sorting.h \
		sources/utilities/sorting_structure.h \
		sources/utilities/string_management.h \
		sources/utilities/timer.h \
		sources/tetrahedral_trees/tree.h \
		sources/tetrahedral_trees/pt_tree.h \
		sources/tetrahedral_trees/t_tree.h \
		sources/tetrahedral_trees/rt_tree.h \
		sources/tetrahedral_trees/p_tree.h \
		sources/main_utility_functions.h \
		sources/queries/spatial_queries.h \
		sources/tetrahedral_trees/node_t.h \
		sources/queries/topological_queries_batched.h \
		sources/basic_types/basic_types.h sources/utilities/sorting.cpp \
		sources/geometry/geometry.cpp \
		sources/geometry/geometry_distortion.cpp \
		sources/geometry/geometry_wrapper.cpp \
		sources/io/reader.cpp \
		sources/io/writer.cpp \
		sources/queries/border_checker.cpp \
		sources/queries/topological_queries.cpp \
		sources/tetrahedral_trees/reindexer.cpp \
		sources/utilities/input_generator.cpp \
		sources/utilities/string_management.cpp \
		sources/utilities/timer.cpp \
		sources/main.cpp \
		sources/queries/spatial_queries.cpp \
		sources/statistics/statistics.cpp \
		sources/basic_types/tetrahedron.cpp \
		sources/tetrahedral_trees/kd_subdivision.cpp \
		sources/tetrahedral_trees/ok_subdivision.cpp \
		sources/tetrahedral_trees/node_t.cpp
QMAKE_TARGET  = tetrahedral_trees
DESTDIR       = dist/
TARGET        = dist/tetrahedral_trees


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d dist/ || mkdir -p dist/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TetrahedralTrees.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		TetrahedralTrees.pro
	$(QMAKE) -o Makefile TetrahedralTrees.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
TetrahedralTrees.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile TetrahedralTrees.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/sorting.o: sources/utilities/sorting.cpp sources/utilities/sorting.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sorting.o sources/utilities/sorting.cpp

build/geometry.o: sources/geometry/geometry.cpp sources/geometry/geometry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/geometry.o sources/geometry/geometry.cpp

build/geometry_distortion.o: sources/geometry/geometry_distortion.cpp sources/geometry/geometry_distortion.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/geometry_distortion.o sources/geometry/geometry_distortion.cpp

build/geometry_wrapper.o: sources/geometry/geometry_wrapper.cpp sources/geometry/geometry_wrapper.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/geometry/geometry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/geometry_wrapper.o sources/geometry/geometry_wrapper.cpp

build/reader.o: sources/io/reader.cpp sources/io/reader.h \
		sources/basic_types/point.h \
		sources/basic_types/box.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h \
		sources/geometry/geometry_wrapper.h \
		sources/geometry/geometry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/reader.o sources/io/reader.cpp

build/writer.o: sources/io/writer.cpp sources/tetrahedral_trees/node.h \
		sources/basic_types/box.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/io/writer.h \
		sources/tetrahedral_trees/tree.h \
		sources/statistics/index_statistics.h \
		sources/statistics/full_query_statistics.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node_t.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/writer.o sources/io/writer.cpp

build/border_checker.o: sources/queries/border_checker.cpp sources/queries/border_checker.h \
		sources/utilities/sorting.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/border_checker.o sources/queries/border_checker.cpp

build/topological_queries.o: sources/queries/topological_queries.cpp sources/queries/topological_queries.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/mesh.h \
		sources/basic_types/box.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h \
		sources/geometry/geometry_wrapper.h \
		sources/geometry/geometry.h \
		sources/geometry/geometry_distortion.h \
		sources/queries/topological_queries_windowed.h \
		sources/queries/border_checker.h \
		sources/utilities/sorting.h \
		sources/utilities/timer.h \
		sources/io/reader.h \
		sources/io/writer.h \
		sources/tetrahedral_trees/tree.h \
		sources/statistics/index_statistics.h \
		sources/statistics/full_query_statistics.h \
		sources/queries/topological_queries_batched.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/topological_queries.o sources/queries/topological_queries.cpp

build/reindexer.o: sources/tetrahedral_trees/reindexer.cpp sources/tetrahedral_trees/reindexer.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/tetrahedral_trees/p_tree.h \
		sources/tetrahedral_trees/tree.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/geometry/geometry_wrapper.h \
		sources/geometry/geometry.h \
		sources/tetrahedral_trees/pt_tree.h \
		sources/utilities/sorting.h \
		sources/tetrahedral_trees/node_t.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/reindexer.o sources/tetrahedral_trees/reindexer.cpp

build/input_generator.o: sources/utilities/input_generator.cpp sources/io/writer.h \
		sources/tetrahedral_trees/tree.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/statistics/index_statistics.h \
		sources/statistics/full_query_statistics.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h \
		sources/utilities/input_generator.h \
		sources/geometry/geometry_wrapper.h \
		sources/geometry/geometry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/input_generator.o sources/utilities/input_generator.cpp

build/string_management.o: sources/utilities/string_management.cpp sources/utilities/string_management.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/string_management.o sources/utilities/string_management.cpp

build/timer.o: sources/utilities/timer.cpp sources/utilities/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/timer.o sources/utilities/timer.cpp

build/main.o: sources/main.cpp sources/main_utility_functions.h \
		sources/geometry/geometry_wrapper.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/geometry/geometry.h \
		sources/io/reader.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h \
		sources/io/writer.h \
		sources/tetrahedral_trees/tree.h \
		sources/statistics/index_statistics.h \
		sources/statistics/full_query_statistics.h \
		sources/queries/spatial_queries.h \
		sources/statistics/statistics.h \
		sources/statistics/query_statistics.h \
		sources/utilities/sorting.h \
		sources/utilities/timer.h \
		sources/queries/topological_queries.h \
		sources/geometry/geometry_distortion.h \
		sources/queries/topological_queries_windowed.h \
		sources/queries/border_checker.h \
		sources/queries/topological_queries_batched.h \
		sources/tetrahedral_trees/ok_subdivision.h \
		sources/tetrahedral_trees/subdivision.h \
		sources/tetrahedral_trees/kd_subdivision.h \
		sources/tetrahedral_trees/p_tree.h \
		sources/tetrahedral_trees/pt_tree.h \
		sources/tetrahedral_trees/t_tree.h \
		sources/tetrahedral_trees/rt_tree.h \
		sources/tetrahedral_trees/reindexer.h \
		sources/utilities/input_generator.h \
		sources/utilities/string_management.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o sources/main.cpp

build/spatial_queries.o: sources/queries/spatial_queries.cpp sources/queries/spatial_queries.h \
		sources/statistics/statistics.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/statistics/query_statistics.h \
		sources/utilities/sorting.h \
		sources/statistics/index_statistics.h \
		sources/statistics/full_query_statistics.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h \
		sources/geometry/geometry_wrapper.h \
		sources/geometry/geometry.h \
		sources/io/writer.h \
		sources/tetrahedral_trees/tree.h \
		sources/io/reader.h \
		sources/utilities/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/spatial_queries.o sources/queries/spatial_queries.cpp

build/statistics.o: sources/statistics/statistics.cpp sources/statistics/statistics.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/box.h \
		sources/statistics/query_statistics.h \
		sources/utilities/sorting.h \
		sources/statistics/index_statistics.h \
		sources/statistics/full_query_statistics.h \
		sources/tetrahedral_trees/node_v.h \
		sources/tetrahedral_trees/node.h \
		sources/tetrahedral_trees/run_iterator.h \
		sources/tetrahedral_trees/node_t.h \
		sources/geometry/geometry_wrapper.h \
		sources/geometry/geometry.h \
		sources/io/writer.h \
		sources/tetrahedral_trees/tree.h \
		sources/io/reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/statistics.o sources/statistics/statistics.cpp

build/tetrahedron.o: sources/basic_types/tetrahedron.cpp sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/tetrahedron.o sources/basic_types/tetrahedron.cpp

build/kd_subdivision.o: sources/tetrahedral_trees/kd_subdivision.cpp sources/tetrahedral_trees/kd_subdivision.h \
		sources/tetrahedral_trees/subdivision.h \
		sources/basic_types/box.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/kd_subdivision.o sources/tetrahedral_trees/kd_subdivision.cpp

build/ok_subdivision.o: sources/tetrahedral_trees/ok_subdivision.cpp sources/tetrahedral_trees/ok_subdivision.h \
		sources/tetrahedral_trees/subdivision.h \
		sources/basic_types/box.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ok_subdivision.o sources/tetrahedral_trees/ok_subdivision.cpp

build/node_t.o: sources/tetrahedral_trees/node_t.cpp sources/tetrahedral_trees/node_t.h \
		sources/tetrahedral_trees/node.h \
		sources/basic_types/box.h \
		sources/basic_types/point.h \
		sources/basic_types/tetrahedron.h \
		sources/utilities/sorting_structure.h \
		sources/basic_types/mesh.h \
		sources/basic_types/vertex.h \
		sources/tetrahedral_trees/run_iterator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/node_t.o sources/tetrahedral_trees/node_t.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

